version: '3.8'

services:
  ejercicio5:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    command: ["./servidor", "-p", "5000", "-u", "10", "-a", "frases.txt"]
    stdin_open: true
    tty: true
    container_name: ahorcado_servidor
    
  cliente5:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "./cliente -n doss -s ahorcado_servidor -p 5000"]
    stdin_open: true
    tty: true
    depends_on:
      - ejercicio5
    profiles:
      - cliente